CREATE TABLE IF NOT EXISTS PUBLIC.CALCULATION_HISTORY_PARAMETERS (
  ID UUID NOT NULL,
  CREDIT DOUBLE PRECISION NOT NULL,
  RATE DOUBLE PRECISION NOT NULL,
  PERIOD INTEGER NOT NULL,
  CALCULATION_HISTORY_ID UUID NOT NULL,
  CONSTRAINT PK_CALCULATION_HISTORY_PARAMETERS PRIMARY KEY (ID),
  CONSTRAINT FK_CALCULATION_HISTORY_PARAMETERS_CALCULATION_HISTORY FOREIGN KEY (CALCULATION_HISTORY_ID) REFERENCES PUBLIC.CALCULATION_HISTORY (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)