CREATE TABLE IF NOT EXISTS PUBLIC.CALCULATION_HISTORY_PAYMENT_INFOS (
  ID UUID NOT NULL,
  PAYMENT_NUMBER INTEGER NOT NULL,
  PAYMENT DOUBLE PRECISION NOT NULL,
  MAIN_DEBT_PAYMENT DOUBLE PRECISION NOT NULL,
  PERCENT_PAYMENT DOUBLE PRECISION NOT NULL,
  DEBT DOUBLE PRECISION NOT NULL,
  CALCULATION_HISTORY_RESULT_ID UUID NOT NULL,
  CONSTRAINT PK_CALCULATION_HISTORY_PAYMENT_INFOS PRIMARY KEY (ID),
  CONSTRAINT FK_CALCULATION_HISTORY_PAYMENT_INFOS_CALCULATION_HISTORY_RESUL FOREIGN KEY (CALCULATION_HISTORY_RESULT_ID) REFERENCES PUBLIC.CALCULATION_HISTORY_RESULTS (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)