CREATE TABLE IF NOT EXISTS PUBLIC.CALCULATION_HISTORY_RESULTS (
  ID UUID NOT NULL,
  PAYMENT DOUBLE PRECISION NULL,
  SUM_PAYMENT DOUBLE PRECISION NOT NULL,
  SUM_MAIN_DEBT_PAYMENT DOUBLE PRECISION NOT NULL,
  SUM_PERCENT_PAYMENT DOUBLE PRECISION NOT NULL,
  MAIN_DEBT_IN_PERCENT DOUBLE PRECISION NOT NULL,
  PERCENTS_IN_PERCENT DOUBLE PRECISION NOT NULL,
  CALCULATION_HISTORY_ID UUID NOT NULL,
  CONSTRAINT PK_CALCULATION_HISTORY_RESULTS PRIMARY KEY (ID),
  CONSTRAINT FK_CALCULATION_HISTORY_RESULTS_CALCULATION_HISTORY FOREIGN KEY (CALCULATION_HISTORY_ID) REFERENCES PUBLIC.CALCULATION_HISTORY (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)