CREATE TABLE IF NOT EXISTS PUBLIC.CALCULATION_HISTORY (
  ID UUID NOT NULL,
  CALC_TYPE INTEGER NOT NULL,
  CREATED_ON TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_CALCULATION_HISTORY PRIMARY KEY (ID)
)