version: '3.8'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api=true
      - --api.dashboard=true
      - --entrypoints.grpc.address=:50051
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.domains[0].main=sanqit.ru
      - --entrypoints.websecure.http.tls.domains[0].sans=*.sanqit.ru
      - --api.debug=true
      - --log=true
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.network=web
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - 80:80
      - 443:443
      - 50051:50051
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.sanqit.ru`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth
      ## Declaring the user list
      ##
      ## Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
      ## sudo apt-get update && sudo apt-get install apache2-utils
      ## To create user:password pair, it's possible to use this command:
      ## echo $(htpasswd -nB admin) | sed -e s/\\$/\\$\\$/g
      ## Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
      - traefik.http.middlewares.traefik-auth.basicauth.users=[htpasswd]
      ## global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      ## middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/deploy/certs/:/certs:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    networks:
      - web